name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop, dev ]
  pull_request:
    branches: [ main, develop, dev ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    services:
      mongodb:
        image: mongo:6.0
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: password
        ports:
          - 27017:27017
        options: >-
          --health-cmd mongosh
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis:7.4-alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: backend/package-lock.json

    - name: Install backend dependencies
      working-directory: ./backend
      run: npm ci

    - name: Run linting
      working-directory: ./backend
      run: npm run lint

    - name: Run unit tests
      working-directory: ./backend
      run: npm run test:unit
      env:
        NODE_ENV: test
        MONGODB_URI: mongodb://root:password@localhost:27017/cuisine-app-test?authSource=admin
        JWT_SECRET: test-secret-key-for-ci
        AUDIT_LOG_DIR: ./tests/temp-logs

    - name: Run integration tests
      working-directory: ./backend
      run: npm run test:integration
      env:
        NODE_ENV: test
        MONGODB_URI: mongodb://root:password@localhost:27017/cuisine-app-test?authSource=admin
        JWT_SECRET: test-secret-key-for-ci
        AUDIT_LOG_DIR: ./tests/temp-logs

    - name: Run all tests with coverage
      working-directory: ./backend
      run: npm run test:coverage
      env:
        NODE_ENV: test
        MONGODB_URI: mongodb://root:password@localhost:27017/cuisine-app-test?authSource=admin
        JWT_SECRET: test-secret-key-for-ci
        AUDIT_LOG_DIR: ./tests/temp-logs

    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      with:
        file: ./backend/coverage/lcov.info
        flags: backend
        name: backend-coverage
        fail_ci_if_error: false

    - name: Build backend
      working-directory: ./backend
      run: npm run build

  security:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        cache-dependency-path: backend/package-lock.json

    - name: Install dependencies
      working-directory: ./backend
      run: npm ci

    - name: Run security audit
      working-directory: ./backend
      run: npm audit --audit-level moderate

    - name: Check for vulnerabilities
      working-directory: ./backend
      run: |
        # Check for high-level vulnerabilities using npm audit exit code
        echo "🔍 Checking for high-level vulnerabilities..."
        echo "📍 Branch: ${{ github.ref_name }}"

        # Run npm audit and capture both output and exit code
        set +e  # Don't exit on error
        audit_output=$(npm audit --audit-level high 2>&1)
        audit_exit_code=$?
        set -e  # Re-enable exit on error

        echo "$audit_output"

        # npm audit exits with code 0 if no vulnerabilities at the specified level
        if [ $audit_exit_code -eq 0 ]; then
          echo "✅ No high-level vulnerabilities found"
          exit 0
        else
          echo "❌ High-level vulnerabilities detected (exit code: $audit_exit_code)"
          exit 1
        fi

  docker:
    runs-on: ubuntu-latest
    needs: [test, security]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build backend image
      uses: docker/build-push-action@v5
      with:
        context: ./backend
        file: ./backend/Dockerfile.prod
        push: false  # Ne jamais pousser depuis dev, seulement construire pour tester
        tags: |
          cuisine-backend:${{ github.ref_name }}
          cuisine-backend:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Notify build status
      run: |
        if [ "${{ github.ref_name }}" = "main" ]; then
          echo "🚀 Image construite pour PRODUCTION (main)"
          echo "⚠️  Docker Hub push disabled - configure DOCKER_USERNAME and DOCKER_PASSWORD secrets to enable"
        elif [ "${{ github.ref_name }}" = "dev" ]; then
          echo "🧪 Image construite pour DÉVELOPPEMENT (dev)"
          echo "✅ Tests Docker build réussis - prêt pour merge vers main"
        else
          echo "🔧 Image construite pour la branche: ${{ github.ref_name }}"
        fi

  deploy:
    runs-on: ubuntu-latest
    needs: docker
    if: github.ref == 'refs/heads/main'  # SEULEMENT sur main
    environment: production

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to production
      run: |
        echo "🚀 Déploiement en PRODUCTION depuis main"
        echo "Image: cuisine-backend:${{ github.sha }}"
        echo "⚠️  Docker Hub push disabled - configure DOCKER_USERNAME and DOCKER_PASSWORD secrets to enable"
        # Ici vous pouvez ajouter vos scripts de déploiement réels
        # Par exemple: mise à jour des services Docker, Kubernetes, etc.

    - name: Notify deployment
      run: |
        echo "✅ Déploiement terminé avec succès"
        echo "Version: ${{ github.sha }}"
        echo "Branche: ${{ github.ref_name }}"
        echo "URL: https://your-production-url.com"
